#!/bin/sh
set -e

VERSION=$1
echo "publishing version: $VERSION"
bun run build

if [ -n "$(git status --porcelain)" ]; then
  echo "git status is dirty"
  exit 1
fi
jq ".version = \"$VERSION\"" package.json > package.json.tmp && mv package.json.tmp package.json
npm publish --tag=ion
git checkout .
