#!/bin/bash
set -e

pnpm build
sed -i.bak -e '3,3d' .changeset/config.json
pnpm changeset version --snapshot 
cp packages/sst/package.json packages/sst/dist/package.json
sed -i.bak -e '2,5d' packages/sst/dist/package.json
pnpm changeset publish --no-git-tag --tag=snapshot
cp .changeset/config.json.bak .changeset/config.json
git checkout '**/package.json' '**/CHANGELOG.md' '.changeset'
