/**
 * DO NOT EDIT THIS FILE DIRECTLY.
 * This file is generated following the conversion of
 * [/home/thdxr/dev/projects/sst/serverless-stack/packages/cli/scripts/util/paths.js]{@link /home/thdxr/dev/projects/sst/serverless-stack/packages/cli/scripts/util/paths.js}
 *
 **/
import { fileURLToPath } from "url";
import { dirname } from "path";
const __dirname = dirname(fileURLToPath(import.meta.url));
import fs from "fs";
import path from "path";
/**
 * Based on https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/config/paths.js
 */
("use strict");

const appDirectory = fs.realpathSync(process.cwd());
const resolveApp = (relativePath) => path.resolve(appDirectory, relativePath);

const resolveOwn = (relativePath) =>
  path.resolve(__dirname, "..", relativePath);

const appBuildDir = ".build";

export default {
  appBuildDir,
  appPath: resolveApp("."),
  appLibPath: resolveApp("./lib"),
  appPackageJson: resolveApp("package.json"),
  appNodeModules: resolveApp("node_modules"),
  appBuildPath: resolveApp(`./${appBuildDir}`),

  ownPath: resolveOwn("../"),
  ownScriptsPath: resolveOwn("../scripts"),
  ownNodeModules: resolveOwn("../node_modules"),
};
