export default {
  async fetch(request: Request): Promise<Response> {
    const html = `<!DOCTYPE html>
    <body>
      <h1>Hello World</h1>
      <p>This markup (in TS) was generated by a Cloudflare Worker.</p>
    </body>`;

    return new Response(html, {
      headers: {
        "content-type": "text/html;charset=UTF-8",
      },
    });
  },
};
