package typescript_test

import (
	"encoding/json"
	"os"
	"path/filepath"
	"testing"

	"github.com/sst/sst/v3/pkg/project/common"
	"github.com/sst/sst/v3/pkg/types/typescript"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func setupProject(t *testing.T, deps map[string]string) string {
	t.Helper()
	dir := t.TempDir()
	pkg := map[string]interface{}{"dependencies": deps}
	data, _ := json.Marshal(pkg)
	os.WriteFile(filepath.Join(dir, "package.json"), data, 0644)
	return dir
}

func TestGenerate(t *testing.T) {
	t.Run("no package.json returns nil", func(t *testing.T) {
		dir := t.TempDir()
		err := typescript.Generate(dir, common.Links{}, nil)
		require.NoError(t, err)
	})

	t.Run("creates sst-env.d.ts with types", func(t *testing.T) {
		dir := setupProject(t, map[string]string{})

		links := common.Links{
			"MyBucket": {
				Properties: map[string]interface{}{
					"name": "my-bucket",
					"arn":  "arn:aws:s3:::my-bucket",
				},
			},
		}

		err := typescript.Generate(dir, links, nil)
		require.NoError(t, err)

		content, err := os.ReadFile(filepath.Join(dir, "sst-env.d.ts"))
		require.NoError(t, err)

		out := string(content)
		assert.Contains(t, out, "auto-generated by SST")
		assert.Contains(t, out, "\"MyBucket\":")
		assert.Contains(t, out, "\"name\": string")
		assert.Contains(t, out, "\"arn\": string")
		assert.NotContains(t, out, "/// <reference path=\"sst-env.d.ts\" />")
	})

	t.Run("number and boolean types", func(t *testing.T) {
		dir := setupProject(t, map[string]string{})

		links := common.Links{
			"Config": {
				Properties: map[string]interface{}{
					"port":    42,
					"rate":    3.14,
					"enabled": true,
				},
			},
		}

		err := typescript.Generate(dir, links, nil)
		require.NoError(t, err)

		content, err := os.ReadFile(filepath.Join(dir, "sst-env.d.ts"))
		require.NoError(t, err)

		out := string(content)
		assert.Contains(t, out, "\"port\": number")
		assert.Contains(t, out, "\"rate\": number")
		assert.Contains(t, out, "\"enabled\": boolean")
	})

	t.Run("nested properties", func(t *testing.T) {
		dir := setupProject(t, map[string]string{})

		links := common.Links{
			"Db": {
				Properties: map[string]interface{}{
					"connection": map[string]interface{}{
						"host": "localhost",
					},
				},
			},
		}

		err := typescript.Generate(dir, links, nil)
		require.NoError(t, err)

		content, err := os.ReadFile(filepath.Join(dir, "sst-env.d.ts"))
		require.NoError(t, err)

		out := string(content)
		assert.Contains(t, out, "\"connection\": {")
		assert.Contains(t, out, "\"host\": string")
	})

	t.Run("sorted keys", func(t *testing.T) {
		dir := setupProject(t, map[string]string{})

		links := common.Links{
			"Thing": {
				Properties: map[string]interface{}{
					"z": "z",
					"a": "a",
				},
			},
		}

		err := typescript.Generate(dir, links, nil)
		require.NoError(t, err)

		content, err := os.ReadFile(filepath.Join(dir, "sst-env.d.ts"))
		require.NoError(t, err)

		out := string(content)
		aIdx := indexOf(out, "\"a\"")
		zIdx := indexOf(out, "\"z\"")
		assert.Greater(t, aIdx, -1)
		assert.Less(t, aIdx, zIdx)
	})

	t.Run("type key quoted at top level", func(t *testing.T) {
		dir := setupProject(t, map[string]string{})

		links := common.Links{
			"MyResource": {
				Type: "aws.s3.Bucket",
				Properties: map[string]interface{}{
					"type": "aws.s3.Bucket",
					"name": "bucket",
				},
			},
		}

		err := typescript.Generate(dir, links, nil)
		require.NoError(t, err)

		content, err := os.ReadFile(filepath.Join(dir, "sst-env.d.ts"))
		require.NoError(t, err)

		out := string(content)
		assert.Contains(t, out, "\"type\": \"aws.s3.Bucket\"")
	})

	t.Run("nested package file is a reference shim", func(t *testing.T) {
		dir := t.TempDir()
		// root package.json
		pkg, _ := json.Marshal(map[string]interface{}{"dependencies": map[string]string{}})
		os.WriteFile(filepath.Join(dir, "package.json"), pkg, 0644)

		sub := filepath.Join(dir, "packages", "web")
		os.MkdirAll(sub, 0755)
		os.WriteFile(filepath.Join(sub, "package.json"), pkg, 0644)

		links := common.Links{
			"MyBucket": {
				Properties: map[string]interface{}{
					"name": "my-bucket",
				},
			},
		}

		err := typescript.Generate(dir, links, nil)
		require.NoError(t, err)

		assert.FileExists(t, filepath.Join(dir, "sst-env.d.ts"))
		assert.FileExists(t, filepath.Join(sub, "sst-env.d.ts"))

		rootContent, err := os.ReadFile(filepath.Join(dir, "sst-env.d.ts"))
		require.NoError(t, err)
		leafContent, err := os.ReadFile(filepath.Join(sub, "sst-env.d.ts"))
		require.NoError(t, err)

		assert.Contains(t, string(rootContent), "\"MyBucket\":")
		assert.Contains(t, string(leafContent), "/// <reference path=\"../../sst-env.d.ts\" />")
		assert.NotContains(t, string(leafContent), "\"MyBucket\":")
	})

	t.Run("rerun updates root but not leaf shim", func(t *testing.T) {
		dir := t.TempDir()
		pkg, _ := json.Marshal(map[string]interface{}{"dependencies": map[string]string{}})
		os.WriteFile(filepath.Join(dir, "package.json"), pkg, 0644)

		sub := filepath.Join(dir, "packages", "web")
		os.MkdirAll(sub, 0755)
		os.WriteFile(filepath.Join(sub, "package.json"), pkg, 0644)

		links1 := common.Links{
			"Bucket": {
				Properties: map[string]interface{}{
					"name": "my-bucket",
				},
			},
		}
		err := typescript.Generate(dir, links1, nil)
		require.NoError(t, err)

		root1, err := os.ReadFile(filepath.Join(dir, "sst-env.d.ts"))
		require.NoError(t, err)
		leaf1, err := os.ReadFile(filepath.Join(sub, "sst-env.d.ts"))
		require.NoError(t, err)

		links2 := common.Links{
			"Bucket": {
				Properties: map[string]interface{}{
					"name": "my-bucket",
				},
			},
			"Table": {
				Properties: map[string]interface{}{
					"name": "my-table",
				},
			},
		}
		err = typescript.Generate(dir, links2, nil)
		require.NoError(t, err)

		root2, err := os.ReadFile(filepath.Join(dir, "sst-env.d.ts"))
		require.NoError(t, err)
		leaf2, err := os.ReadFile(filepath.Join(sub, "sst-env.d.ts"))
		require.NoError(t, err)

		assert.NotEqual(t, string(root1), string(root2))
		assert.Equal(t, string(leaf1), string(leaf2))
	})

	t.Run("repairs broken leaf shim", func(t *testing.T) {
		dir := t.TempDir()
		pkg, _ := json.Marshal(map[string]interface{}{"dependencies": map[string]string{}})
		os.WriteFile(filepath.Join(dir, "package.json"), pkg, 0644)

		sub := filepath.Join(dir, "packages", "web")
		os.MkdirAll(sub, 0755)
		os.WriteFile(filepath.Join(sub, "package.json"), pkg, 0644)
		os.WriteFile(filepath.Join(sub, "sst-env.d.ts"), []byte("broken"), 0644)

		err := typescript.Generate(dir, common.Links{}, nil)
		require.NoError(t, err)

		leafContent, err := os.ReadFile(filepath.Join(sub, "sst-env.d.ts"))
		require.NoError(t, err)

		assert.Contains(t, string(leafContent), "/// <reference path=\"../../sst-env.d.ts\" />")
		assert.NotContains(t, string(leafContent), "broken")
	})

	t.Run("cloudflare explicit type is used exactly", func(t *testing.T) {
		dir := setupProject(t, map[string]string{})

		links := common.Links{
			"MyKV": {
				Properties: map[string]interface{}{"name": "my-kv"},
				Include: []common.LinkInclude{
					{Type: "cloudflare.binding"},
					{Type: "typescript.type", Other: map[string]interface{}{"value": `import("custom/types").KV`}},
				},
			},
		}

		err := typescript.Generate(dir, links, nil)
		require.NoError(t, err)

		content, err := os.ReadFile(filepath.Join(dir, "sst-env.d.ts"))
		require.NoError(t, err)
		assert.Contains(t, string(content), `"MyKV": import("custom/types").KV`)
	})

	t.Run("first-party non-binding type preserves its explicit object shape", func(t *testing.T) {
		dir := setupProject(t, map[string]string{})

		err := typescript.Generate(dir, common.Links{
			"MySite": {
				Properties: map[string]interface{}{"url": "https://example.com"},
				Include: []common.LinkInclude{{
					Type:  "typescript.type",
					Other: map[string]interface{}{"value": "{ url: string }"},
				}},
			},
		}, nil)
		require.NoError(t, err)

		content, err := os.ReadFile(filepath.Join(dir, "sst-env.d.ts"))
		require.NoError(t, err)
		assert.Contains(t, string(content), `"MySite": { url: string }`)
	})

	t.Run("cloudflare binding without explicit type returns an error", func(t *testing.T) {
		dir := setupProject(t, map[string]string{})

		links := common.Links{
			"MyKV": {
				Properties: map[string]interface{}{
					"name": "my-kv",
				},
				Include: []common.LinkInclude{
					{Type: "cloudflare.binding"},
				},
			},
		}

		err := typescript.Generate(dir, links, nil)
		require.Error(t, err)
		assert.Contains(t, err.Error(), "MyKV")
	})

	t.Run("malformed and duplicate explicit types return errors", func(t *testing.T) {
		tests := []struct {
			name    string
			include []common.LinkInclude
		}{
			{
				name: "malformed",
				include: []common.LinkInclude{{
					Type:  "typescript.type",
					Other: map[string]interface{}{"value": 42},
				}},
			},
			{
				name: "duplicate",
				include: []common.LinkInclude{
					{Type: "typescript.type", Other: map[string]interface{}{"value": "A"}},
					{Type: "typescript.type", Other: map[string]interface{}{"value": "B"}},
				},
			},
		}

		for _, test := range tests {
			t.Run(test.name, func(t *testing.T) {
				dir := setupProject(t, map[string]string{})
				err := typescript.Generate(dir, common.Links{
					"Resource": {Include: test.include},
				}, nil)
				require.Error(t, err)
			})
		}
	})

	t.Run("cloudflare leaf gets reference shim like aws", func(t *testing.T) {
		dir := t.TempDir()
		pkg, _ := json.Marshal(map[string]interface{}{"dependencies": map[string]string{}})
		os.WriteFile(filepath.Join(dir, "package.json"), pkg, 0644)

		sub := filepath.Join(dir, "packages", "web")
		os.MkdirAll(sub, 0755)
		cfPkg, _ := json.Marshal(map[string]interface{}{"dependencies": map[string]string{"@cloudflare/workers-types": "^4.0.0"}})
		os.WriteFile(filepath.Join(sub, "package.json"), cfPkg, 0644)

		links := common.Links{
			"MyBucket": {
				Properties: map[string]interface{}{
					"name": "my-bucket",
				},
			},
			"MyKV": {
				Properties: map[string]interface{}{
					"name": "my-kv",
				},
				Include: []common.LinkInclude{
					{Type: "cloudflare.binding"},
					{Type: "typescript.type", Other: map[string]interface{}{"value": `import("@cloudflare/workers-types").KVNamespace`}},
				},
			},
		}

		err := typescript.Generate(dir, links, nil)
		require.NoError(t, err)

		rootContent, err := os.ReadFile(filepath.Join(dir, "sst-env.d.ts"))
		require.NoError(t, err)
		leafContent, err := os.ReadFile(filepath.Join(sub, "sst-env.d.ts"))
		require.NoError(t, err)

		// Root has everything including Cloudflare augmentations
		assert.Contains(t, string(rootContent), "\"MyBucket\":")
		assert.Contains(t, string(rootContent), "\"MyKV\":")
		assert.Contains(t, string(rootContent), `import("@cloudflare/workers-types").KVNamespace`)

		// Leaf is just a reference shim
		assert.Contains(t, string(leafContent), "/// <reference path=\"../../sst-env.d.ts\" />")
		assert.NotContains(t, string(leafContent), "\"MyBucket\":")
		assert.NotContains(t, string(leafContent), "\"MyKV\":")
	})

	t.Run("ignores configured directories", func(t *testing.T) {
		dir := t.TempDir()
		pkg, _ := json.Marshal(map[string]interface{}{"dependencies": map[string]string{}})
		os.WriteFile(filepath.Join(dir, "package.json"), pkg, 0644)

		ignored := filepath.Join(dir, "packages", "docs")
		included := filepath.Join(dir, "packages", "web")
		os.MkdirAll(ignored, 0755)
		os.MkdirAll(included, 0755)
		os.WriteFile(filepath.Join(ignored, "package.json"), pkg, 0644)
		os.WriteFile(filepath.Join(included, "package.json"), pkg, 0644)

		err := typescript.Generate(dir, common.Links{}, []string{"packages/docs"})
		require.NoError(t, err)

		assert.FileExists(t, filepath.Join(dir, "sst-env.d.ts"))
		assert.FileExists(t, filepath.Join(included, "sst-env.d.ts"))
		_, err = os.Stat(filepath.Join(ignored, "sst-env.d.ts"))
		assert.True(t, os.IsNotExist(err))
	})

	t.Run("cloudflare durable object binding types", func(t *testing.T) {
		dir := setupProject(t, map[string]string{})

		pkg, _ := json.Marshal(map[string]interface{}{
			"devDependencies": map[string]string{
				"@cloudflare/workers-types": "^4.0.0",
			},
		})
		os.WriteFile(filepath.Join(dir, "package.json"), pkg, 0644)

		links := common.Links{
			"Counter": {
				Include: []common.LinkInclude{
					{Type: "cloudflare.binding"},
					{Type: "typescript.type", Other: map[string]interface{}{"value": `import("@cloudflare/workers-types").DurableObjectNamespace`}},
				},
			},
		}

		err := typescript.Generate(dir, links, nil)
		require.NoError(t, err)

		content, err := os.ReadFile(filepath.Join(dir, "sst-env.d.ts"))
		require.NoError(t, err)

		out := string(content)
		assert.Contains(t, out, `"Counter": import("@cloudflare/workers-types").DurableObjectNamespace`)
	})
}

func indexOf(s, substr string) int {
	for i := 0; i <= len(s)-len(substr); i++ {
		if s[i:i+len(substr)] == substr {
			return i
		}
	}
	return -1
}
