package typescript

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/sst/sst/v3/internal/fs"
	"github.com/sst/sst/v3/pkg/project/common"
)

var header = strings.Join([]string{
	"/* This file is auto-generated by SST. Do not edit. */",
	"/* tslint:disable */",
	"/* eslint-disable */",
	"/* deno-fmt-ignore-file */",
	"/* biome-ignore-all lint: auto-generated */",
	"",
	"",
}, "\n")

var footer = strings.Join([]string{
	"",
	"import \"sst\"",
	"export {}",
}, "\n")

func Generate(root string, links common.Links, ignore []string) error {
	explicitTypes := map[string]string{}
	for name, link := range links {
		foundBinding := false
		foundType := false
		for _, include := range link.Include {
			if include.Type == "cloudflare.binding" {
				foundBinding = true
			}
			if include.Type == "typescript.type" {
				if foundType {
					return fmt.Errorf("link %q has duplicate typescript.type includes", name)
				}
				foundType = true
				value, ok := include.Other["value"].(string)
				if !ok || strings.TrimSpace(value) == "" {
					return fmt.Errorf("link %q has malformed typescript.type include", name)
				}
				explicitTypes[name] = value
			}
		}
		if foundBinding && !foundType {
			return fmt.Errorf("Cloudflare binding link %q is missing typescript.type", name)
		}
	}

	packageJsons := fs.FindDownWithIgnore(root, "package.json", ignore)
	rootEnv := filepath.Join(root, "sst-env.d.ts")

	resources := map[string]interface{}{}
	for name, link := range links {
		if value, ok := explicitTypes[name]; ok {
			resources[name] = literal{value: value}
		} else {
			resources[name] = link.Properties
		}
	}
	rootContent := renderRootFile(resources)

	for _, packageJson := range packageJsons {
		envPath := filepath.Join(filepath.Dir(packageJson), "sst-env.d.ts")

		content := ""
		if rootEnv == envPath {
			content = rootContent
		} else {
			rel, err := filepath.Rel(filepath.Dir(envPath), rootEnv)
			if err != nil {
				continue
			}
			content = renderReferenceFile(filepath.ToSlash(rel))
		}

		if err := os.WriteFile(envPath, []byte(content), 0644); err != nil {
			continue
		}
	}

	return nil
}

func renderRootFile(resources map[string]interface{}) string {
	var builder strings.Builder
	builder.WriteString(header)
	builder.WriteString("declare module \"sst\" {\n")
	builder.WriteString("  export interface Resource ")
	builder.WriteString(infer(resources, "  "))
	builder.WriteString("\n")
	builder.WriteString("}\n")
	builder.WriteString(footer)
	return builder.String()
}

func renderReferenceFile(rel string) string {
	var builder strings.Builder
	builder.WriteString(header)
	builder.WriteString("/// <reference path=\"")
	builder.WriteString(rel)
	builder.WriteString("\" />\n")
	builder.WriteString(footer)
	return builder.String()
}

type literal struct {
	value string
}

func infer(input map[string]interface{}, indentArgs ...string) string {
	indent := ""
	if len(indentArgs) > 0 {
		indent = indentArgs[0]
	}
	var builder strings.Builder
	builder.WriteString("{")
	builder.WriteString("\n")
	keys := make([]string, 0, len(input))
	for key := range input {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	for _, key := range keys {
		value := input[key]
		builder.WriteString(indent + "  \"" + key + "\": ")
		if key == "type" && len(indentArgs) == 1 {
			builder.WriteString("\"")
			builder.WriteString(value.(string))
			builder.WriteString("\"")
		} else {
			switch v := value.(type) {
			case literal:
				builder.WriteString(v.value)
			case string:
				builder.WriteString("string")
			case int:
				builder.WriteString("number")
			case float64:
				builder.WriteString("number")
			case float32:
				builder.WriteString("number")
			case bool:
				builder.WriteString("boolean")
			case map[string]interface{}:
				builder.WriteString(infer(value.(map[string]interface{}), indent+"  "))
			default:
				builder.WriteString("any")
			}
		}
		builder.WriteString("\n")
	}
	builder.WriteString(indent + "}")
	return builder.String()
}
