#!/bin/sh

bun build ./functions/nodejs-runtime/index.ts --target=node --outdir ./dist/nodejs-runtime/
bun build ./functions/cf-static-site-router-worker/index.ts --target=node --outdir ./dist/cf-static-site-router-worker/