#!/bin/bash

git fetch --force --tags

# Get the latest Git tag
latest_tag=$(git tag --sort=committerdate | grep -E '[0-9]' | tail -1)

# If there is no tag, exit the script
if [ -z "$latest_tag" ]; then
    echo "No tags found"
    exit 1
fi

echo "Latest tag: $latest_tag"

# Split the tag into major, minor, and patch numbers
IFS='.' read -ra VERSION <<< "$latest_tag"

# Increment the patch version
patch_number=${VERSION[2]}
let "patch_number++"

# Construct the new version
new_version="${VERSION[0]}.${VERSION[1]}.$patch_number"

echo "New version: $new_version"

git tag $new_version
git push --tags
