name: Assign New Issues to Project

on:
  issues:
    types: [opened, reopened]

jobs:
  issue_opened_or_reopened:
    name: issue_opened_or_reopened
    runs-on: ubuntu-latest
    if: github.event_name == 'issues' && (github.event.action == 'opened' || github.event.action == 'reopened')
    steps:
      - name: Move issue to project
        uses: leonsteinhaeuser/project-beta-automations@v1.2.0
        with:
          gh_token: ${{ secrets.FWANG_ASSIGN_ISSUES_TO_PROJECT_TOKEN }}
          organization: sst
          project_id: 1
          resource_node_id: ${{ github.event.issue.node_id }}
          status_value: Triage
